#!/bin/bash

: ${VERSION:=0.11.3}

VOLUME="/data"
DOCKER_IMAGE_NAME="lonecyprus/terraform"
DOCKER_IMAGE="${DOCKER_IMAGE_NAME}:${VERSION}"
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

volume_option="-v "$(pwd):$VOLUME""
if [[ ! -z "${SHARED_VOLUME}" ]]; then
  volume_option="--volumes-from ${SHARED_VOLUME}"
fi

set -eu

[[ -z "${AWS_ACCESS_KEY_ID}" ]] && { echo "\$AWS_ACCESS_KEY_ID environment variable is empty" ; return 1; }
[[ -z "${AWS_SECRET_ACCESS_KEY}" ]] && { echo "\$AWS_SECRET_ACCESS_KEY environment variable is empty" ; return 1; }
[[ -z "${AWS_DEFAULT_REGION}" ]] && { echo "\$AWS_DEFAULT_REGION environment variable is empty" ; return 1; }

if [[ "$(docker images -q ${DOCKER_IMAGE} 2> /dev/null)" == "" ]]; then
  curl -s https://raw.githubusercontent.com/lone-cyprus/docker-bin/master/Dockerfile.terraform \
    | docker build -f - \
                   --build-arg GITHUB_TOKEN=$TF_VAR_github_token \
                   --build-arg VERSION=$VERSION \
                   -t $DOCKER_IMAGE \
                   .
fi

docker run --rm -t $(tty &>/dev/null && echo "-i") \
           -e "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}" \
           -e "AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}" \
           -e "AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}" \
           ${volume_option} \
           -w $VOLUME \
           $DOCKER_IMAGE "$@"
