#!/bin/bash

: ${VERSION:=latest}

readonly aws_region=us-east-2

VOLUME="/data"
DOCKER_IMAGE_NAME="lonecyprus/terraform"
DOCKER_IMAGE="${DOCKER_IMAGE_NAME}:${VERSION}"
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

volume_option="-v "$(pwd):$VOLUME""
if [[ ! -z "${SHARED_VOLUME}" ]]; then
  volume_option="--volumes-from ${SHARED_VOLUME}"
fi

set -eu

[[ -z "${AWS_ACCESS_KEY_ID}" ]] && { echo "\$AWS_ACCESS_KEY_ID environment variable is empty" ; return 1; }
[[ -z "${AWS_SECRET_ACCESS_KEY}" ]] && { echo "\$AWS_SECRET_ACCESS_KEY environment variable is empty" ; return 1; }
[[ -z "${AWS_DEFAULT_REGION}" ]] && { echo "\$AWS_DEFAULT_REGION environment variable is empty" ; return 1; }

docker_repo="$(VERSION=latest aws ecr get-authorization-token --region ${aws_region} --output text --query 'authorizationData[].proxyEndpoint')"
docker_repo="${docker_repo/$'\r'/}"
readonly ecr_endpoint="${docker_repo#https://}"

VERSION=latest aws ecr get-login --no-include-email --region ${aws_region} | awk '{print $6}' | docker login -u AWS --password-stdin ${docker_repo}

docker pull "${ecr_endpoint}/${DOCKER_IMAGE}"

docker run --rm -t $(tty &>/dev/null && echo "-i") \
           -e "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}" \
           -e "AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}" \
           -e "AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}" \
           ${volume_option} \
           -w $VOLUME \
           "${ecr_endpoint}/${DOCKER_IMAGE}" "$@"
